service: pdm-ui
runtime: python37

basic_scaling:
  max_instances: 1

handlers:
  - url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|jpg|jpeg|gif|png|json|pdf))
    static_files: build/\1
    upload: build/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|jpg|jpeg|gif|png|json|pdf))
    secure: always

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always
